source "https://rubygems.org"
ruby "2.6.3"
gem "jekyll", "~> 3.7"
gem "minimal-mistakes-jekyll"
group :jekyll_plugins do
  gem "jekyll-remote-theme"
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
  gem "jekyll-feed", "~> 0.6"
  gem "jemoji"
  gem "jekyll-include-cache"
  gem "kramdown-parser-gfm"
  gem "jekyll-archives"
end