---
# Source: datapower-operator/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datapower-operator
  labels:
    app.kubernetes.io/instance: datapower-operator
    app.kubernetes.io/name: datapower-operator
    app.kubernetes.io/managed-by: datapower-operator
---
# Source: datapower-operator/templates/cluster_role_binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: datapower-operator
  labels:
    app.kubernetes.io/instance: datapower-operator
    app.kubernetes.io/name: datapower-operator
    app.kubernetes.io/managed-by: datapower-operator
subjects:
- kind: ServiceAccount
  name: datapower-operator
  namespace: metadata.namespace
roleRef:
  kind: ClusterRole
  name: datapower-operator
  apiGroup: rbac.authorization.k8s.io
---
# Source: datapower-operator/templates/operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datapower-operator
  labels:
    app.kubernetes.io/instance: datapower-operator
    app.kubernetes.io/name: datapower-operator
    app.kubernetes.io/managed-by: datapower-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: datapower-operator
      app.kubernetes.io/name: datapower-operator
      app.kubernetes.io/managed-by: datapower-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: datapower-operator
        app.kubernetes.io/name: datapower-operator
        app.kubernetes.io/managed-by: datapower-operator
      annotations:
        productID: datapower-operator
        productName: "IBM DataPower Operator"
        productVersion: 1.0.0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "beta.kubernetes.io/arch"
                operator: In
                values: ["amd64"]
      topologySpreadConstraints:
      - maxSkew: 0
        topologyKey: zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: datapower-operator
            app.kubernetes.io/name: datapower-operator
            app.kubernetes.io/managed-by: datapower-operator
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: datapower-operator
      imagePullSecrets:
      - name: ibm-entitlement-key
      containers:
        - name: datapower-operator
          # Replace this with the built image name
          image: ibmcom/datapower-operator:1.0.0
          command:
          - datapower-operator
          args:
          - "--zap-encoder=json"
          - "--zap-level=info"
          - "--zap-time-encoding=iso8601"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "datapower-operator"
            - name: NAMESPACED_NAME
              value: datapower-operator
            - name: IBM_ENTITLED_REGISTRY
              value: "cp.icr.io/cp/datapower"
            - name: IBM_DOCKER_HUB
              value: "docker.io/ibmcom"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: 2
              memory: "2Gi"
          securityContext:
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
