swagger: '2.0'
info:
  title: loopback
  x-ibm-name: loopback
  version: 1.0.0
schemes:
  - https
basePath: /loopback
securityDefinitions:
  extoauth:
    type: oauth2
    flow: password
    x-ibm-oauth-provider: thirdpartyoidc
    tokenUrl: >-
      https://eu-de.appid.cloud.ibm.com/oauth/v4/8794b41b-4705-4381-a96e-46dfabf3f249/token
    scopes:
      audit: audit scope to access API
      execute: scope to access API with scope execute
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - gatewayscript:
          version: 2.0.0
          title: gatewayscript
          source: |-
            var response = {"echo":"success"};
            context.message.body.write(JSON.stringify(response));
  application-authentication:
    certificate: false
paths:
  /echo:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
      consumes: []
      produces: []
      security:
        - extoauth:
            - audit
          clientID: []
  /execute:
    get:
      responses:
        '200':
          description: success
          schema:
            type: object
      security:
        - clientID: []
          extoauth:
            - execute
      consumes: []
      produces: []
